### ISSUE TITLE
My Book Page Modal for a book - Claire approved for Kim and Collin 

### ISSUE THREAD

**Issue by vanwykkim** [CascadeColin/book-buddy#81]
- [x] - have checkbox options for what shelf to put book add delete button KIM  
- [x]  COLIN hook up checkboxes and delete button
- [x]  - Delete Book Button on Modal - deletes book and closes modal (hard refresh screen?)  - Colin hook up
- [ ]  Future Function Change if Time - make book cover the button not open button below (COLIN)
- [ ] use purple button on model to add star rating on each book feature (NICOLE) maybe Colin?

**Comment by CascadeColin** [comment]
3/5 complete, the other 2 won't be possible with the time we have left.  Closed for now, but will re-open this when dev resumes.
