### ISSUE TITLE
Book Search

### ISSUE THREAD

**Issue by vanwykkim** [CascadeColin/book-buddy#95]
- [ ] Add title of book searched to error message (NICOLE)
- [ ] clear screen of last searched book and prior errors on submit and show new errors or book (COLIN)

**Comment by CascadeColin** [comment]
Future development issue - I did the best I could with the API we are using.  There are enough working books to run a presentation.  Going to change it to chatGPT (gpt-3.5-turbo) next week but didn't want to risk running infinite loops on a paid API during development.  I'm on the waitlist for gpt-4.

**Comment by CascadeColin** [comment]
PR up for a change to addDesc() (fn that filters data into a description).  It'll return "No description available!" more often, but we'll also get a matching book more often.
